language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.2
  - jruby-9.1.5.0
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rake --version
before_script:
  - bundle exec rake --version
script: bundle exec rspec
#
# Environment variables should be set in Travis repository settings per
# https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
#
# Required vars are SONAR_API_URL, SONAR_EMAIL, and SONAR_TOKEN
#
